apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Flux Demo</title>
    </head>
    <body>
      <h1>Version 5.6</h1>
    </body>
    </html>
